services:
  nebula:
    image: portainer/portainer-ce:latest
    container_name: nebula-portainer
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "9000:9000"   # UI Portainer
      - "8000:8000"   # Edge (opcional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - avengers_net

networks:
  avengers_net:
    name: avengers_net
    driver: bridge
