services:
  gamora:
    image: jc21/nginx-proxy-manager:latest
    container_name: gamora-proxy
    restart: unless-stopped
    # Adicionado bloco de vari√°veis de ambiente
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
      - "81:81"   # Painel admin
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - avengers_net

networks:
  avengers_net:
    name: avengers_net
    driver: bridge
